### ISSUE TITLE
Organize Contents

### ISSUE THREAD

**Issue by decoded-cipher** [akash-santhosh/tools#10]
- Can't we keep the contents more organized, so that in the future one could use this repo to its fullest potential?
- How about separating the contents based on something:
  - Categorize it stack-wise
  - Separate the non-stack Tools

**Comment by akash-santhosh** [comment]
sure thing. Im changing this from markdown to next,js

**Comment by akash-santhosh** [comment]
@decoded-cipher could do help me with that, also, this is in nextjs
